version: '3.8'

services:
  academic-time-tracker:
    image: academic-time-tracker:latest
    container_name: academic-time-tracker
    ports:
      - "5000:5000"
    volumes:
      # Use proper Unraid appdata path
      - /mnt/user/appdata/academic-time-tracker/data:/app/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/groups"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s